### ISSUE TITLE
Install traffic analytics 

### ISSUE THREAD

**Issue by andrei-rizoiu** [behavioral-ds/behavioral-ds.github.io#12]
Nice to have feature: could we have traffic tracking and analysis installed on the website? Obvious choose is Google Analytics, but others may be better suited.

**Comment by rohitram96** [comment]
I've added a identifier in the `params.toml` in b688a08682b9aa6be7b522f1087e3fc3f4fab3f9 ; hopefully this works, but I'll check in 24 hours. 

If this doesn't work, we might need to update the google analytics partial to the most recent one.

**Comment by rohitram96** [comment]
![image](https://user-images.githubusercontent.com/13506150/99892029-81555f00-2cc4-11eb-94fc-0f7c3c2c2ad9.png)
And Analytics are working. This is currently linked to my google account, but I can share a link privately for people to view.
