### ISSUE TITLE
Add link to news archive on main page

### ISSUE THREAD

**Issue by andrei-rizoiu** [behavioral-ds/behavioral-ds.github.io#29]
On the main page, we have a selection of recent news. Can we have a link to the news archive under **Recent News** (See mockup).
![image](https://user-images.githubusercontent.com/13706841/115134252-e33aaa80-a051-11eb-9746-75c05090f09b.png)

**Comment by piocalderon** [comment]
resolved with the ff commit: https://github.com/behavioral-ds/behavioral-ds.github.io/commit/95cd63c2a78e7a07213338112b13fbd0155c041f
