### ISSUE TITLE
Build after pull requests does not result in updated website

### ISSUE THREAD

**Issue by andrei-rizoiu** [behavioral-ds/behavioral-ds.github.io#3]
The automatic build succeeds after the pull request merges, however, the generated website does not show the changes. It still shows the version before the build.

**Comment by andrei-rizoiu** [comment]
See the current status of the website, after commit 3e06fce8332111066e12e83b64c90a365c26f5c7 . It should show Dima's profile, but it doesn't.

**Comment by andrei-rizoiu** [comment]
The workaround seems to be building the website locally, and push all generated files, which seems to defeat the purpose of the autobuild.

**Comment by rohitram96** [comment]
Not entirely sure why it's not updating. It might be worth moving to netlify to deploy; this works for me more often. @qykong any ideas?

**Comment by qykong** [comment]
it appears this is Github slowly propagating the changes. I can see just now the updates from yesterday so there's about 10+ hour delay. Happy with moving to netlify if that works better

**Comment by andrei-rizoiu** [comment]
Which changes have propagated? I have generated the html after yaozhong's pull request and pushed (so not generated by github). We can wait to see if some of the later pull requests get rendered.

Marian-Andrei Rizoiu.
http://www.rizoiu.eu

________________________________

**Comment by qykong** [comment]
@andrei-rizoiu i was referring to Yaozhong's update. If that's case, I guess it was from your push then.. I'll dig a bit more into this

**Comment by qykong** [comment]
Sorry, this appears to be a bug in the deploy workflow. I've fixed this and proper deployments should happen immediately now after every commit. Closing the issue for now and feel free to reopen if the issue persists.
