### ISSUE TITLE
Clicking on the research item in the bar menu only expands the menu

### ISSUE THREAD

**Issue by andrei-rizoiu** [behavioral-ds/behavioral-ds.github.io#31]
At the moment, the only way to get to the research page is by selecting one of the options in the research submenu. Would it be possible to simply click on "Research", and take me to the top ?

**Comment by piocalderon** [comment]
Resolved here: 
https://github.com/behavioral-ds/behavioral-ds.github.io/commit/baac34b6d53d45c26b0cf8e31b0f30cbdcd33687
