### ISSUE TITLE
The website does no longer gets deployed automatically at pushes

### ISSUE THREAD

**Issue by andrei-rizoiu** [behavioral-ds/behavioral-ds.github.io#35]
The push failed for commit 0e5be27f880b263c8dea3a2f2095e15d38cecf1d and nothing happened for 0ce5050b (despite the green tickmark next to the commit).

**Expected outcome:** Frankie's paper today (all you need is love) should appear in the reading list.

**Comment by qykong** [comment]
Turns out to be a temporary issue with GitHub
