### ISSUE TITLE
Removing the resources cache prior to push makes autobuild to fail

### ISSUE THREAD

**Issue by andrei-rizoiu** [behavioral-ds/behavioral-ds.github.io#4]
The folder `/resources/_gen` contains auto-generated files (such as image thumbnails etc). The files in that folder are generated when running `hugo`. Removing them locally and re-running hugo regenerates the folder and build succeeds.

However, when removing the folder prior to pushing (or adding to  `/gitignore` file) results in a failed build.

**Comment by rohitram96** [comment]
Looking into the Actions tab, the error points to versioning as the reason for the build fail. It might be the case that the version used for building by the auto-build is too old (0.60.1). I'm locally running 0.74.3; could you check what version you're running (`hugo version`)? We might need to update the version used in building.

**Comment by andrei-rizoiu** [comment]
From memory, I use v0.61.xx (default in Ubuntu 20.04 ?)

Marian-Andrei Rizoiu.
http://www.rizoiu.eu

________________________________

**Comment by qykong** [comment]
The new update to the Action workflow fixed this as well. It appears we need to use the hugo extended versions which add support for SCSS.
