### ISSUE TITLE
Add a link to all posts under recent posts

### ISSUE THREAD

**Issue by andrei-rizoiu** [behavioral-ds/behavioral-ds.github.io#48]
Add under "Recent posts" a link to the posts collection, just like for the "Recent News" (see printscreen)
![image](https://user-images.githubusercontent.com/13706841/148329600-cb78edc6-8427-44f3-9250-f99915ce6fac.png)

**Comment by piocalderon** [comment]
added post archive link https://github.com/behavioral-ds/behavioral-ds.github.io/commit/22eb74ee5562e8288a98d9c32fb9447e583847e3

looks slightly different as news and posts are handled differently in the template. for posts, i simply tagged all posts with the Post category and referred to the Post category page
